### ISSUE TITLE
bug: the backspace in insert model  doesn't work

### ISSUE THREAD

**Issue by yuandong1222** [coolceph/vimrc#13]
I update my vimrc by 
1) cd ~/.vim
2) git pull
3) setup -u

The error is :
E117: Unknown function: neocomplete#smart_close_popup
E15: Invalid expression: neocomplete#smart_close_popup()."^H"
Press ENTER or type command to continue

**Comment by yuandong1222** [comment]
I tried to source ~/.zshrc, nothing happens.

**Comment by ketor** [comment]
Maybe somethin wrong during your git pull & git submodule update process.
Should you try to install from vimrc-xxxxxxxx.tar.gz?
http://pan.baidu.com/s/1hrqLnu8

The steps is:
1. scp vimrc-xxxxxxxx.tar.gz to ~
2. tar -zxvf vimrc-xxxxxxxx.tar.gz
3. ~/.vim/setup.sh -l

The latest version add auto-completion using clang. You should yum install clang to enable vim-clang complete. It's very cool!!!!!

I've tested this steps on CentOS7.2 in QingCloud, all is ok.

Also when I use git clone & git submodule init/update, because of the great firewall network problem, git cannot finished easily and then I see warn & err in vim.

**Comment by yuandong1222** [comment]
It works. THX.
